server:
    address: 0.0.0.0
    port: 8686
    servlet:
        context-path: /product

#数据源配置
spring:
    servlet:
        multipart:
            maxFileSize: 50MB
            maxRequestSize: 100MB
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://192.168.30.216:3306/hunansta?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
        #url: jdbc:mysql://192.168.36.83:3306/hunansta?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
        #url: jdbc:mysql://192.168.1.115:3306/hunansta?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
        url: jdbc:mysql://127.0.0.1:3306/pro?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
        username: root
        #password: taro@VIP2018
        #password: hunansta
        #password: taro@VIP
        password: root
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        filters: stat,wall,log4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        useGlobalDataSourceStat: true
        validationQuery: SELECT 1 FROM DUAL
    activiti:
        check-process-definitions: false
    redis:
        database: 0   			# Redis数据库索引（默认为0）
        host: 127.0.0.1 		# Redis服务器地址
        pool:
            max-active: 8		# 连接池最大连接数（使用负值表示没有限制）
            max-idle: 8			# 连接池中的最大空闲连接
            max-wait: -1		# 连接池最大阻塞等待时间（使用负值表示没有限制）
            min-idle: 0			# 连接池中的最小空闲连接
        port: 6379				# Redis服务器连接端口
        timeout: 2000			# 连接超时时间（毫秒）

#日志配置文件地址
logging:
    config: classpath:logback-spring.xml

#mybatis配置
mybatis:
    mapper-locations: classpath*:mybatis/**/*Mapper.xml
    type-aliases-package: com.taro.entity.*

#pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    params: count=countSql
    reasonable: true
    supportMethodsArguments: true

#系统个性化配置
singleUserLogin: 0

fileManage: 
    uploadPath: D:/upload/
    
borunkeji:
    flow:
        username: borunkeji
        password: Borun123
